platform: linux

image: docker:///ruby#2.1

inputs:
- name: p-concourse
- name: final-release
- name: garden-linux-release
- name: version

outputs:
- name: product

run:
  path: p-concourse/ci/scripts/build.sh
